package com.example.mymoviecatalogapp;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import java.util.ArrayList;


public class MainActivity extends AppCompatActivity {
    private ArrayList<Movie> movies;
    private RecyclerView rvCategory;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        rvCategory = findViewById(R.id.rv_category);

        movieData();

        showRecyclerCardView();
    }

    public void showRecyclerCardView() {
        rvCategory.setLayoutManager(new LinearLayoutManager(this));
        CardViewMovieAdapter cardViewMovieAdapter = new CardViewMovieAdapter(this);
        cardViewMovieAdapter.setListMovie(movies);
        rvCategory.setAdapter(cardViewMovieAdapter);

        ItemClickSupport.addTo(rvCategory).setOnItemClickListener(new ItemClickSupport.OnItemClickListener() {
            @Override
            public void onItemClicked(RecyclerView recyclerView, int position, View v) {
                showSelectedMovie(movies.get(position));
            }
        });
    }

    private void showSelectedMovie(Movie movie) {
        Intent movieDetail = new Intent(MainActivity.this, MovieDetail.class);

        movieDetail.putExtra("EXTRA_MOVIE", movie);
        startActivity(movieDetail);
    }

    private void movieData() {
        movies = new ArrayList<>();
        movies.add(new Movie("Lion King (2019)", "7.2", "1h 58m", "EN", "Simba idolises his father, King Mufasa, and takes to heart his own royal destiny. But not everyone in the kingdom celebrates the new cub's arrival...", "Director Jon Favreau (Iron Man) teams up with screenwriter Jeff Nathanson (Pirates of the Caribbean: Dead Men Tell No Tales) to create a new, fully CGI version of the Disney classic, The Lion King. And while the story doesn't vary too much from the original, the live-action look and feel brings freshness to the tale - as well as a real, raw, and sometimes scary nature.\n" +
                "\n" +
                "Simba (JD McCrary) is the budding young protégé of his father Mufasa (James Earl Jones), who teaches him about the kingdom of the Pridelands - a massive expanse in which the circle of life, a delicate balance of nature, is maintained. But Mufasa's brother, Scar (Chiwetel Ejiofor), is jealous of both his sibling and his nephew, and he hatches a ruthless plan destined to ravage the homeland and make himself ruler. A much older Simba (Donald Glover) must gain the courage and understanding it takes to assume his rightful place, or else the Pridelands will permanently become as barren as an elephant graveyard.\n" +
                "\n" +
                "With the animated feature as beloved as it is, there is a lot of tradition to acknowledge. Favreau and Nathanson work hard and tread lightly, doing a respectable job of honoring Brenda Chapman's original story. Neither becomes too heavy-handed in the changes, only making minor exclusions and additions and keeping a decent balance in appreciating the original tale and enhancing it with newer elements that make more sense in this format.\n" +
                "\n" +
                "A lot of the freshness comes from enthusiastic voice performances of the cast. Jones reprising his role from the original is a treat and helps create a comfort zone between the two films. Ejiofor's performance evokes an even more sinister villain, along with the hyenas, led by Florence Kasumba's Shenzi. Seth Rogen and Billy Eichner are entertaining as Pumbaa and Timon, leading Simba into maturity, while Glover and Beyoncé nicely fill out the roles of adult Simba and Nala.\n" +
                "\n" +
                "The CGI is exceptional, often looking more like a documentary about nature than a computer-animated film. This might be a slight problem for some younger members of the audience because there are a few scenes that are darker in tone, and the realism makes them more frightening. The film seems geared towards a slightly older audience than the original. Despite this high quality, there is a noticeable problem with the animation. In several close-up scenes, the emotion the actors give us does not come through in the characters. Instead, they are almost doll-like in their expressions and results in the film's biggest shortcoming.\n" +
                "\n" +
                "Still, the movie is otherwise of exceptional quality, and everyone involved clearly wanted to make sure they created something fun, updated, and respectful that makes the audience feel completely immersed in a more natural world. They have succeeded, and audiences of all ages should be able to enjoy the updated look almost as much as the original.\n" +
                "\n" +
                "Now, those who took their children to see it in 1994 can take their grandchildren too. And because of the quality, they can do it with pride.", "https://image.tmdb.org/t/p/w600_and_h900_bestv2/dzBtMocZuJbjLOXvrl4zGYigDzh.jpg", "https://www.youtube.com/watch?v=7TavVZMewpY"));
        movies.add(new Movie("Avengers: End Game (2019)", "8.4", "3h 1m", "EN", "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos...", "Directors Anthony and Joe Russo, along with writers Christopher Markus and Stephen McFeely, return to the Marvel Universe to finish what they started by giving us Avengers: Endgame. And while it isn't quite as good as Infinity War, it is still a well-rounded tale that comes very close to the level of the prior film.\n" +
                "\n" +
                "Thanos (Josh Brolin) has won the Infinity War, and with a snap of his fingers, half the life in the universe has been eliminated from existence. It seems that there is nothing the heroes can do until Ant-Man (Paul Rudd) shows up on the steps of the Avengers Mansion. In order to find a way to defeat Thanos and undo what he has done, the original six members of the Avengers, as well as the few other remaining superheroes, reunite in a desperate effort. But against the power of the Infinity Gauntlet, how can they hope to win?\n" +
                "\n" +
                "The script opens with a bang, making sure you know what you're in for. Unfortunately, it falters a little from there. There are comedic moments, and each one is spot-on, but as they often call for dialogue in some of the more serious times, they seem too lighthearted. Ultimately, it slows down the pace of the film for a while until the characters and script get down to more serious business. The deeper the characters get into the quest, the more appropriately dramatic the story gets, right down to an epic conclusion that is perfectly fitting for the final film in Phase 3 of the Marvel Cinematic Universe.\n" +
                "\n" +
                "From the actors with the most prominent roles to those making guest appearances, each one played their role to franchise perfection. This is a sign of their continued dedication to the characters, but also a statement of the control the directors exerted in making this entry flow directly from the previous films in the series. Robert Downey Jr. as Tony Stark / Iron Man is particularly impressive, convincingly transforming himself as needed throughout the film. Jeremy Renner (Tag) gives his best performance yet as Clint Barton, aka Hawkeye, while Chris Hemsworth (The Cabin in the Woods) is hilariously entertaining as Thor.\n" +
                "\n" +
                "The action is hot and heavy, particularly in the intense battle near the end, but there aren't any noticeable flaws in the flow of the special effects or CGI. There is a lot to see there, and even though there are a few scenes that are hard to keep up with, it never gets blurry - just crowded. Credit the cinematography for keeping the action mostly on-point.\n" +
                "\n" +
                "Despite its early story flaws, Avengers: Endgame is extremely entertaining, with a memorable cast and script that delivers to audience expectations. It also leaves plenty of room to wonder what will happen as we step into the new game of the Marvel Cinematic Universe - Phase Four.", "https://image.tmdb.org/t/p/w600_and_h900_bestv2/or06FN3Dka5tukK1e9sl16pB3iy.jpg", "https://www.youtube.com/watch?v=TcMBFSGVi1c"));
        movies.add(new Movie("Spider-Man: Far From Home (2019)", "7.8", "2h 9m", "EN", "Peter Parker and his friends go on a summer trip to Europe...", "Despite being a comedic success, Spider-Man: Far From Home is far from a perfect movie. Director Jon Watts' command of moving chess pieces and villains is obvious, compared to other Marvel films. Although chaos permeates the action and special effects, the film somehow manages to revive something that has been missing in past live-action superhero films: a sensibility for its teen audience.\n" +
                "\n" +
                "It doesn't get talked about enough but Spider-Man (and many other superheroes) caters to either the very young broods who dress up as the character on Halloween night or to the adults who grew up loving the character and still cling to it. This isn't to say superheroes aren't for adults too, but between those two demographics, teens get lost in the shuffle. Of all the superhero films, Far From Home, even with its flaws, best caters to teenagers. In fact, one could argue Far From Home is more a teen comedy and less an actual superhero film. The humor is nestled perfectly among mild sensuality, goofy awkwardness, and overall campiness.\n" +
                "\n" +
                "In the story, Peter Parker (Tom Holland) is out of Queens and travelling to Europe on a class trip. It's a risky move to uproot a character from his proverbial stomping grounds, especially one as codified as the \"friendly, neighborhood Spider-Man.\" But as Nick Fury (Samuel L. Jackson) says, \"you've been to space!\" However, Spider-Man is still just a Spider-teenager at heart, and teens primarily want one thing: to hang out with their friends and significant others. The main struggle for Peter in this film is that he just wants to be a teenager.\n" +
                "\n" +
                "Unfortunately, monsters and villains run amok in Europe, too. Even more unfortunate is how the set pieces for these conflicts are constructed in Far From Home. The extremely fast-paced action combined with dominant special effects create rampaging sequences that are hard to digest. Spider-Man's foray into the villain's \"illusion tech\" later on in the movie is so dense with effects and manic pacing that the audience never has a chance to really feel any stakes at all. Instead, it feels more as though special effects are splashed onto the screen and the audience.\n" +
                "\n" +
                "Nonetheless, humor is a saving grace for this Spidey film. It largely stands out thanks to Ned (Jacob Batalon), Peter Parker's best friend. His unique stage presentation and delivery have him stealing scenes left and right. For instance, the casual, recalling joke of Ned saying, \"Aw, babe\" in tandem with his girlfriend is hilarious. Zendaya as M.J. also makes a mark with her gloomy Daria-esque spin on the traditionally doe-eyed character.\n" +
                "\n" +
                "Out of all the Peter Parkers, Holland is by far the best at portraying an actual teenager. Tobey Maguire didn't quite look the part and though Andrew Garfield was slightly better in that department, he mimicked the sarcastic, spry path set down by Maguire. Holland's version of Peter lacks certainty and confidence, even with all he has done and every person he has saved. Even the way he carries himself is very unsure. But every iteration of Spider-Man has brought us closer and closer to a true teen superhero: goofy, awkward, and confused. Spider-Man: Far From Home is the culmination of that fact, even if it's buried under excessive effects.", "https://image.tmdb.org/t/p/w600_and_h900_bestv2/rjbNpRMoVvqHmhmksbokcyCr7wn.jpg", "https://www.youtube.com/watch?v=Nt9L1jCKGnE"));
        movies.add(new Movie("Fast & Furious Presents: Hobbs & Shaw (2019)", "6.6", "2h 16m", "EN", "A spinoff of The Fate of the Furious, focusing on Johnson's US Diplomatic Security Agent...", "As a new addition to the Fast & Furious franchise, David Leitch directs Hobbs & Shaw, with its over-the-top and well-choreographed, CGI action sequences, delivers a comparable, if not larger adrenaline rush than its predecessors. However, it falls short in terms of its plot, depth, and substance, leaving the audience with a typical, smash 'em-up Hollywood flick.\n" +
                "\n" +
                "American DSS agent Luke Hobbs (Dwayne 'The Rock' Johnson) and Deckard Shaw (Jason Statham), a British 'good guy' mercenary, are reluctantly thrown together (again) to take on a totalitarian-thinking organization's plot to unleash a bio-harnessed virus into the world, leaving only the fittest to survive. Shaw's sister, Hattie (Vanessa Kirby), also a highly skilled mercenary, becomes infected with the virus, which must be extracted from her body in order to save her life. The dynamic, mutually sarcastic, comedic duo of Hobbs and Shaw must break into an almost impenetrable facility, run by the totalitarian organization located in Moscow, in order to retrieve a device that can extract the virus from Hattie's body. Their prime nemesis, Brixton (Idris Elba), a former ally of Shaw and now an elite killer for the ill-intentioned organization, has since had 'mechanical' upgrades to his body, giving him super-human abilities. He must counter their efforts and take control of the virus inhabited by Hattie in order to carry out the organization's master plan of using the virus as a bioweapon. As the conflict between both rivals ensues, an all-out pandemonium results in a multi-continental battle as both sides race to accomplish their goal.\n" +
                "\n" +
                "Despite well-timed banter between Hobbs and Shaw with their relentless alpha-male verbal attacks, the script and dialogue miss the mark in terms of making an impact. There are decent elements to the back-stories of the characters, but it doesn't capture its potential depth; the script was too fluffy and the dialogue too trite. However, it's the charisma and on-screen chemistry that allow for Hobbs & Shaw to rise above what is otherwise an average Hollywood action film. The family dynamic between Hattie and Deckard is strong but unrealized chemistry between Hattie and Hobbs disappoints. Still, a few surprise cameos help to bring a bit more of a 'punch' to the film.\n" +
                "\n" +
                "Cinematically speaking, the action-packed visuals are on par with any big budget Hollywood film. Although the acting, for an action film, is good and helps thrust the film forward, the almost-predictable, verbal jabs between the main characters leaves a watered-down version of what could have alternatively been a more meaningful story and screenplay. In other words, although funny at times, less would have been more. From an entertainment standpoint, the direction holds up in terms of its visual storytelling and incorporation of cutting-edge CGI, but it lacks in the multi-dimensional sense of how vital emotion can be in action-packed scenes. Indeed, there are stunning shots and sequences, but depth is lacking.\n" +
                "\n" +
                "Except for young children, almost any age group, if in the mood for non-stop sarcasm and hard-hitting Hollywood action, will enjoy the two-hour Hobbs & Shaw film ride. What the audience will not get, is a multi-layered and artistically driven film in terms of storytelling. The first take-away message from the film is that irrespective of how far we take technology, the 'will' of the human spirit will always supersede the inorganic. And secondly, there is always room for forgiveness and unconditional love with family - no matter how much time passes.", "https://image.tmdb.org/t/p/w600_and_h900_bestv2/keym7MPn1icW1wWfzMnW3HeuzWU.jpg", "https://www.youtube.com/watch?v=HZ7PAyCDwEg&t=67s"));
        movies.add(new Movie("Alita: Battle Angel (2019)", "6.8", "2h 2m", "EN", "When Alita awakens with no memory of who she is in a future world she does not recognize...", "In Alita: Battle Angel, director Robert Rodriguez (Spy Kids) steps into the limelight again, this time taking a script by James Cameron (Avatar) based on the classic manga serial by the same name and bringing it to the big screen.\n" +
                "\n" +
                "While searching for cybernetic scrap, Dr. Dyson Ido (Christoph Waltz) discovers the unbelievable - a still functional cyborg core he names \"Alita\" (Rosa Salazar). Although she has no memory of who she is or what happened to her, it quickly becomes clear that she is no ordinary being. As she experiences more of the new world around her Alita begins to understand more of her past, even as new loyalties begin to shape her future.\n" +
                "\n" +
                "Cameron is a masterful storyteller, and the Alita script is no exception. There is a lot of room for predictability in a story that has been told numerous times already - that of someone whose past is a mystery and whose purpose becomes clear as the tale progresses - but many of the expected things do not happen. In his typical style, Cameron throws surprising curves. There are a few moments that go as expected, as well as a few call-outs to previous Cameron movies, but it is mostly fresh and entertaining.\n" +
                "\n" +
                "Rodriquez has a particular style of direction in his action films, and you can feel his presence throughout. He manages to pull great performances from all of his lead actors - even when they aren't fully actors at all. We seem to have finally reached that point where CGI metahumans and protohumans manage completely realistic and complex facial expressions, helping the scene rather than distracting from it. The only unfortunate thing that remains from this is, occasionally, some of the flesh-and-blood actors seem to be looking through the CGI characters rather than at them.\n" +
                "\n" +
                "Other than that, the leads give solid performances. Waltz is both caring and troubled, showing additional range from previous characterizations. Jennifer Connelly and Mahershala Ali are solid, although a bit underused, as antagonists. Rosa Salazar as Alita is the gem of the performances. She is alternately vulnerable and violent in perfect measures, and her emotions and movements translate through the motion capture exceptionally well.\n" +
                "\n" +
                "The action, and there is a lot of it, is not overwhelming as in some films. It does have moments that it moves so quickly that it can be hard to keep up with, but never because of blurring. There is just so much happening that it is nearly impossible to see it all.\n" +
                "\n" +
                "The biggest flaw the film may be its greatest strength and that is the lack of a clearly defined lead villain. Instead, we get a lot of players in a complex game that isn't over yet, even with the removal of some pieces. While the story comes to an acceptable close, it is clear that there is more to the tale, just the way Cameron likes it.\n" +
                "\n" +
                "Alita: Battle Angel is a great action-adventure film, featuring a solid cast, a strong female lead, and a story that is complete on its own, but leaves plenty of blanks left to fill in a sequel.", "https://image.tmdb.org/t/p/w600_and_h900_bestv2/xRWht48C2V8XNfzvPehyClOvDni.jpg", "https://www.youtube.com/watch?v=cislZ9S0ocA"));
        movies.add(new Movie("Captain Marvel (2019)", "7.0", "2h 4m", "EN", "The story follows Carol Danvers as she becomes one of the universe’s most powerful heroes when Earth is caught in the middle of a galactic war between two alien races...", "Captain Marvel crashes into the big screen with a flurry of explosions. The titular superheroine (Brie Larson) embodies the toughest bruiser imaginable as she fistfights, flies, and shoots her way through the stratosphere without so much as a glance over her shoulder to watch the carnage. This endless action ride pauses momentarily only for laughs and character development as new friends bond.\n" +
                "\n" +
                "Sandwiched between two epic intergalactic films that tie the entire Marvel Universe together, Captain Marvel incorporates the first female lead in a Marvel film, focusing on the story of the origins of the superheroine. It weaves several different epic superhero stories together, throwing them into a universal battle of good vs. evil, ultimately deciding all their fates, as well as everyone in existence. The stakes are astronomical.\n" +
                "\n" +
                "The film requires a healthy attention span along with plenty of focus. The element of being thrown into the 1990's could throw off devoted fans of the series. But in so doing, we discover that the infinity war may be connected to Captain Marvel's alter ego on Earth, Carol Danvers.\n" +
                "\n" +
                "Being thrust into this infinity war is a lot for one woman to bear, no matter how heroic she may be. But Captain Marvel gets some early advice from her mentor Yon-Rogg (Jude Law) to keep her potentially dangerous emotions in check. The humans think differently, suggesting that these feelings are what make you a hero. There are plenty of opportunities for her to develop emotionally upon discovering that she may have led a significant life on Earth prior to becoming a fighter pilot for the Kree (alien good guys).\n" +
                "\n" +
                "Captain Marvel contains cutting-edge special effects so realistic, it's hard to distinguish what's real from what's been altered. Of note are the younger visage of Nick Fury (Samuel L. Jackson) with both eyes intact, as well as a full head of hair, and a scene-stealing CGI alien/best friend/copilot/cat, aptly named Goose.\n" +
                "\n" +
                "Captain Marvel struggles with two very tough cinematic challenges in addition to her numerous foes. First, this film falls between the two other major Avengers Infinity War movies. With so many new characters mandatory for her to befriend, it draws focus away from the story of her provenance. Second, Marvel sometimes dips into \"Superman territory,\" where the protagonist is so invincible that the audience isn't emotionally invested because there's no way for the character to die.\n" +
                "\n" +
                "To spice up the mix, writing and directing partners Anna Boden and Ryan Fleck (Half Nelson, Sugar) bring their indie film brand of mixing comedy and emotion to a genre traditionally void of these things. Although it broadens its appeal to a wider audience, the frenetic action is non-stop. Adding the pop grunge soundtrack including: Nirvana, Garbage, and No Doubt is a sly trick to tie together 90's cultural themes in Captain Marvel's coming-of-age story.\n" +
                "\n" +
                "Ultimately, with so many thrills, laughs, and terse combat scenes, the lack of any romance is a breath of fresh air. This fierce girl-power flick could be a stand-alone launch for the new Captain Marvel series, and it's an absolute must-see for fans of the Marvel Universe.", "https://image.tmdb.org/t/p/w600_and_h900_bestv2/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg", "https://www.youtube.com/watch?v=0LHxvxdRnYc"));
        movies.add(new Movie("Aladdin (2019)", "7.1", "2h 10m", "EN", "A kindhearted street urchin named Aladdin embarks on a magical adventure after finding a lamp that releases a wisecracking genie...", "Director Guy Ritchie (Sherlock Holmes: A Game of Shadows, Snatch), doing double-duty as scriptwriter with John August, brings us the next step in Disney's live-action versions of its classic animated films with Aladdin. Despite its obvious source material, there is just enough new and different to make this film a fresh entry.\n" +
                "\n" +
                "Aladdin (Mena Massoud) is a common street urchin whose life consists of barely surviving - eking out an existence somewhere between thief and beggar. But his life takes a dramatic turn from a chance encounter with Princess Jasmine (Naomi Scott), and then the Royal Vizier, Jafar (Marwan Kenzari). Jafar recruits him to retrieve a magical item from the Cave of Wonders, which brings Aladdin face-to-face with the Genie (Will Smith) and a potential new destiny that lies far from simply wondering how he will eat that day.\n" +
                "\n" +
                "Much of the screenplay is sourced from the original, although there are some changes to the story, mostly filling in a little more background. These changes are primarily solid, adding depth of character to the portrayals, as well as additional motivations. Iago (voiced by Alan Tudyk) is the exception. While seemingly more evil than his original, he is also less developed and lacks personality. Also, while Jafar's motivations are more rounded, his character seems more greedy than he is evil, which is a loss.\n" +
                "\n" +
                "Each actor seems to be a near-perfect casting choice, with the exception of Jafar. Kenzari's performance suffers less from a lack of talent than a lack of character, though he does do quite well with what he has to work with. Had the character been written to be as diabolical as the original, there is no doubt he would have been up to the task. Massoud brings fun and lightheartedness to Aladdin, making him a character the viewer can both enjoy and care about. The real stars of the cast are Naomi Scott and Will Smith. Rather than fill some very big shoes, Smith chose to make the Genie as much his own as possible, to the benefit of the overall film.\n" +
                "\n" +
                "Overall, it is good that they take a strong character in Jasmine and make her stronger, adding more power and self-determination. This makes her an even better role model than the original as she joins into the action more frequently rather than ever truly being a \"damsel in distress.\" Additionally, the decision to make her more concerned for the country and its people than her potential fate was inspired.\n" +
                "\n" +
                "Like Smith, Scott takes the character of Jasmine and owns it, making her someone much more than just what the script called for. Unfortunately, Alan Menken added a song where Jasmine talks about what she is going to do rather doing it. This detracts from her actually taking action. When she finally does, it strengthens her character even more, but the song dilutes this growth just a little.\n" +
                "\n" +
                "For the most part, the cinematography is lavish and beautiful. Long shots are rich in color, depicting an Agrabah that is much more alive than the original 1992 version. The special effects are spectacular, sometimes better than the original. However, there is an exception. The flying carpet scene with Aladdin and Jasmine was determined to be so important that it is barely altered, rendering it needlessly dull.\n" +
                "\n" +
                "Overall, it is good that they take a strong character in Jasmine and make her stronger, adding more power and self-determination. This makes her an even better role model than the original as she joins into the action more frequently rather than ever truly being a \"damsel in distress.\" Additionally, the decision to make her more concerned for the country and its people than her potential fate was inspired.\n" +
                "\n" +
                "All in all, Aladdin is a decent film. There will doubtless be those who say it is too much like the original film, just as there will be those who say it is too little. Both sets of moviegoers would do well to look at Aladdin as its own film, as they will be much more likely to see the diamond in the rough.", "https://image.tmdb.org/t/p/w600_and_h900_bestv2/3iYQTLGoy7QnjcUYRJy4YrAgGvp.jpg", "https://www.youtube.com/watch?v=foyufD52aog"));
        movies.add(new Movie("How to Train Your Dragon (2019)", "7.6", "1h 44m", "EN", "As Hiccup fulfills his dream of creating a peaceful dragon utopia, Toothless’ discovery of an untamed, elusive mate draws the Night Fury away...", "How to Train Your Dragon: The Hidden World brings an emotional honesty rare to kids' films and a visual appeal of the highest caliber. A coming-of-age story for both the boy and his dragon, it's also another lesson about the possibility of finding something deeper in interactions with nature.\n" +
                "\n" +
                "Writer/Director Dean DeBlois (How to Train Your Dragon, Lilo & Stitch) delivers another sumptuous visual treat, filled with wonder, fantasy and enough awkward moments to make you want to facepalm. The flying scenes are more engaging and gorgeous than its predecessors, while the emotional scenes have more to build on, as the characters are now maturing into adulthood.\n" +
                "\n" +
                "Hiccup (Jay Baruchel) has taken over as the leader of his village after the unfortunate passing of his father at the hands (or more accurately the fiery breath) of his dragon, Toothless. His leadership style is the exact opposite of his dad and he sets about rescuing all the dragons his village once vowed to slay. There is trouble in paradise though, as their dragon population is growing faster than their resources.\n" +
                "\n" +
                "Grimmel the Grisly (F. Murray Abraham) is a dragon hunter bent on capturing Hiccups' best friend Toothless, the rare Night Fury. He has an army of Vikings and dragons who serve him, though his plan is to lure Toothless out with another rare dragon: the female Light Fury.\n" +
                "\n" +
                "Hiccups's friend and inevitable love interest Astrid (America Ferrera) provides a strong female character to yank Hiccup out of his boyish ways and into manhood. Their intentionally laughable romance mirrors the dragon romance between Toothless and the new Light Fury dragon he falls for.\n" +
                "\n" +
                "What transpires is nothing less than an epic journey across the ocean and to the edge of the earth as they search for the \"Hidden World.\" This may be an allegory for the hidden passions buried in their youthful hearts and the strong connections they continue to form toward their promised land. It is also a literal journey with some simple positive messages including respecting the land and its inhabitants and learning to let go of what you love.\n" +
                "\n" +
                "The one forgivable bump may be in reintroducing so many characters in a film that only runs for 104 minutes, although they all have enough snark, or emotional presence to justify their continued existence in the series. Despite the constant peril at every moment, almost everyone miraculously makes it out alive.\n" +
                "\n" +
                "The PG rating allows the film to stay true to its original form, but still leaves plenty of age-appropriate laughs for kids, as well as enough storyline to keep the adults interested. Although this was promised to be the final film in the series, the high-yield franchise that fans have grown to love could easily be extended for another few movies.", "https://image.tmdb.org/t/p/w600_and_h900_bestv2/xvx4Yhf0DVH8G4LzNISpMfFBDy2.jpg", "https://www.youtube.com/watch?v=SkcucKDrbOI"));
        movies.add(new Movie("Godzilla: King of The Monsters (2019)", "6.3", "2h 12m", "EN", "Follows the heroic efforts of the crypto-zoological agency Monarch as its members face off against a battery of god-sized monsters, including the mighty Godzilla...", "Godzilla: King of the Monsters is a big, bad basher film, with the emphasis on both big and bad. No worse than any of the other films in the franchise, there are enough buildings crushed to overlook some of the major failures that the shaky camerawork and overuse of hazy weather can't hide. Connected to Kong: Skull Island and a sequel to 2014's Godzilla, this installment is co-written and directed by Michael Dougherty (Trick 'r Treat) whose horror background shows its ugly face in Godzilla: King of the Monsters. Although the fight choreography is a lot of fun, the two-dimensional characters who have little to say don't add any value, and the required elements for a better movie are left out.\n" +
                "\n" +
                "An eco-terrorist (Charles Dance) kidnaps a scientist (Vera Farmiga) and her daughter (Millie Bobby Brown), along with their mind-control device to be used on giant monsters called 'Titans.' He's hoping to harness his captives' power in order to destroy humanity, which he believes will save the world. However, he doesn't count on Godzilla to annihilate all his classic foes: Mothra, Rhodan, and King Ghidorah.\n" +
                "\n" +
                "To modernize this monster movie, the filmmakers attempt to focus on the humans to scale the emotional impact. The actors chosen to embody the different characters are great, but the script is so poorly written that they can't do much to demonstrate their presence on screen. Fans of Godzilla come to see monsters and mayhem; they don't need scientific explanations or family drama to try to make it anything more than visceral pleasure from watching things break. In that respect, Godzilla: King of the Monsters does finally deliver a huge smash 'em up fight scene spanning the final 30 minutes of the film. But that is confusing for viewers who witness the long, dramatic beginning which amounts to very little other than the characters just watching carnage unfold.\n" +
                "\n" +
                "For a summer spectacle, it would that bigger is better, but Godzilla himself has very little screen time in his own movie. Though not boring, the film lacks the appropriate amount of destruction. It's also hard to spot giant monsters in a film that's basically just about giant monsters; fog, rain, nighttime darkness, and all kinds of things hide the baddies when they finally do appear, and then there are quick cutaways to horrified humans reacting to the fight that the audience can't see properly.\n" +
                "\n" +
                "Ultimately, Godzilla: King of the Monsters provides enough sizzle that the low-quality steak may be partially forgiven. Aided by the high budget, the sound and visuals are great, which is enough to pump some adrenaline through the more boring moments of the film. The feature length version doesn't do much beyond expanding the trailer. The momentum is slowed for what everyone came to see - monsters bashing monsters.", "https://image.tmdb.org/t/p/w600_and_h900_bestv2/pU3bnutJU91u3b4IeRPQTOP8jhV.jpg", "https://www.youtube.com/watch?v=QFxN2oDKk0E"));
        movies.add(new Movie("Shazam! (2019)", "7.0", "2h 12m", "EN", "A boy is given the ability to become an adult superhero in times of need with a single magic word...", "Director David F. Sandberg (Annabelle: Creation) tackles a script by Henry Gayden (Zombie Roadkill) that works hard to make the classic 1940's character relevant in the ever-expanding realm of the comic book adaptation film. But instead of aiming for the serious tones of more recent films in the genre, Gayden gives us a mix of drama and comedy with very entertaining results.\n" +
                "\n" +
                "Billy Batson (Asher Angel) is a troublesome kid in search of his real mother. In and out of different foster homes, he seems the furthest thing from the best of humanity. But the Wizard Shazam (Djimon Hounsou) is out of options. Thaddeus Sivana (Mark Strong), once drawn to the cave and rejected by the wizard, has found a way back there. Allied with the embodiment of the Seven Deadly Sins, he seeks to destroy humanity. As a 14-year old, Billy must take on the role of Shazam (Zachary Levi) in an adult's body, learn his abilities, and stop Sivana from succeeding.\n" +
                "\n" +
                "The story seems far-fetched, but somehow it works. The script is far from perfect, and in fact, it drags at times while developing some characters and neglecting others. Most notably is Silvana, who never really becomes a villain the audience cares about. The portrayal is plastic, more an effect of the scripting than the actor. This is countered by the phenomenal performance of Levi as Shazam. He clearly remembers what it was like to be fourteen, and both he and the script capture that in an effective manner.\n" +
                "\n" +
                "The script's earlier flubs can be forgiven by a stalwart portrayal of what it means to be family and how our true relatives are often not those we are related to by blood. This arc progresses nicely in quite an organic manner, solidifying as the film comes to a close.\n" +
                "\n" +
                "The special effects are spot on, especially in scenes when Billy is learning his capabilities. The Sins are disturbing, as they should be, but it would have been more impressive if the audience could clearly distinguish them. The music throughout the film was very organic, setting a background tone when needed, and in your face at all the appropriate times.\n" +
                "\n" +
                "There is some graphic violence as well as scary moments that are not going to be appropriate for younger audiences, so the PG-13 rating is well earned.\n" +
                "\n" +
                "All told, Shazam is a better-than-average superhero film, partly because the genre has been turned onto its ear and partly despite it. It provides good entertainment, some genuine laughs, and a closing story worth watching and remembering.", "https://image.tmdb.org/t/p/w600_and_h900_bestv2/xnopI5Xtky18MPhK40cZAGAOVeV.jpg", "https://www.youtube.com/watch?v=go6GEIrcvFY"));
        movies.add(new Movie("Pokemon Detective Pikachu (2019)", "7.0", "1h 45m", "EN", "In a world where people collect pocket-size monsters (Pokémon) to do battle, a boy comes across an intelligent monster who seeks to be a detective...", "Rob Letterman (Goosebumps) directs and co-writes Pokémon Detective Pikachu to bring favorite childhood characters to life in all their CGI glory. And while the story is solid and the film is generally fun, it could have used a bit more emotional investment between the characters to truly put it over the top.\n" +
                "\n" +
                "Tim Goodman (Justice Smith) seems to be the only person to NOT have a personal Pokémon. Even his estranged police detective father has his own Pikachu as a partner. Just when he is taking an interest in having one, he learns that his father has been killed in an auto accident. To settle his father's affairs he travels to Ryme City, where humans and Pokémon live and work together in harmony. There, he encounters that Pikachu (voiced by Ryan Reynolds) who insists that Tim's father is alive. Together, they embark on a quest to find out what really happened in the accident.\n" +
                "\n" +
                "The story is satisfying, although a little slow early on. Most of this comes from a lack of emotional connections, both between characters and also with the audience. This is the primary stumble in an otherwise solid tale.\n" +
                "\n" +
                "Whether it is the story, the direction, or the acting, the characters are less believable somehow. They come across as more like characters on a flat page than on a big screen. Even veteran Bill Nighy as media conglomerate head Howard Clifford isn't as engaging as he could have been. Ryan Reynolds channels a mostly-G version of his Deadpool into Pikachu, and even this feels like a missed opportunity until later in the film. Kathryn Newton (Blockers) as reporter wanna-be Lucy Stevens is the best asset as the strong, sometimes frantic female that all incarnations of Pokémon require.\n" +
                "\n" +
                "As with anything Pokémon, the Pokémon themselves are the real stars, and CGI looks really good on them. Even though their scenes are usually easy to follow, viewers will be hard-pressed to see everyone in a single showing. They are vivid, cleanly meshed with the humans… and EVERYWHERE, especially in and around Ryme City. Now-adult fans of the television series will enjoy trying to catch 'em all.\n" +
                "\n" +
                "Pokémon Detective Pikachu is a good film and a strong first entry into CGI for the large cast of fantastic creatures. Enjoyable for any audience, it will be primarily loved by those looking back at the series nostalgically. Hopefully, there are more future opportunities for us to see Pikachu and friends protect the world from devastation.", "https://image.tmdb.org/t/p/w600_and_h900_bestv2/wgQ7APnFpf1TuviKHXeEe3KnsTV.jpg", "https://www.youtube.com/watch?v=du88WArjb8w"));
        movies.add(new Movie("Hellboy (2019)", "5.0", "2h 1m", "EN", "Hellboy comes to England, where he must defeat Nimue, Merlin's consort and the Blood Queen. But their battle will bring about the end of the world, a fate he desperately tries to turn away...", "Hellboy is back, this time under the direction of Neil Marshall (Dog Soldiers). Rebooting with a new cast and revived characters, the Andrew Cosby (Eureka) script delivers a story that, while decent, may leave fans of the previous movies a little cold for its lack of character engagement.\n" +
                "\n" +
                "Hellboy (David Harbour) is an agent of the Bureau of Paranormal Research and Defense, helping his father, Professor Broom (Ian McShane) against powerful supernatural entities that wish to do mankind harm. But, after a betrayal and subsequent rescue by his powerful, medium friend, Alice Monaghan (Sasha Lane), he doubts his place in human society. To complicate matters, Nimue the Blood Queen (Milla Jovovich) has plans to rid the world of humanity, using Hellboy's power to do so. Caught in the middle, Hellboy must decide whether to save humanity or doom it forever.\n" +
                "\n" +
                "The story is rather complete, despite a few hitches with its implementation. There are seemingly inauthentic interpersonal relationships, and viewers get the impression that they need to know more about several of the characters on both sides of the battle, including their preexisting motivations. The brief back-stories come across as more of an afterthought than actual development. This is especially true of Nimue, who after having her origins revealed in the opening scene, drifts in and out of the film just to be menacing.\n" +
                "\n" +
                "The direction is clean, but a premeditated decision to make the film much like a comic book both helps and harms it. It romps along at a fun pace, but there are moments that are just too overdone. The decision to make the film rated R conceptually allows it to be more like the original comics, but in practice, it just appears to be an excuse to add more CGI gore. The CGI includes amazingly detailed creatures and settings. Most of the renderings are beautiful, although in some moments it overwhelms in quantity and pace. All these scenes have accompanying, accurately selected rock-and-roll music that you might expect Hellboy to be listening to while he smashes things.\n" +
                "\n" +
                "When it's not slightly over-the-top, the acting is excellent. Jovovich is sensually creepy, Lane is a strong sidekick, and McShane is gruff, grumpy, yet caring. The best of the crop, though, is David Harbour, taking over the mantle of the titular role, and wearing it hilariously well. He seems a near-perfect replacement from the start.\n" +
                "\n" +
                "Hellboy's biggest problem is that neither the original director nor lead actor return for the long-awaited third installment, but instead opt for a hard reboot. If audiences can put aside their disappointment in this respect, they might discover that despite some flaws, the film is worth seeing in its own right.", "https://image.tmdb.org/t/p/w600_and_h900_bestv2/bk8LyaMqUtaQ9hUShuvFznQYQKR.jpg", "https://www.youtube.com/watch?v=ZsBO4b3tyZg"));
    }
}
